name: completion
on:
  push:
  pull_request:
    branches: [master]
jobs:
  completion-spec:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Run completion specs
        run: make spec_completion
