name: completion

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Run conmpetion tests
        run: make spec_completion
