name: check-formatting
on:
  push:
  pull_request:
    branches: [master]
jobs:
  format:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Check formatting 
        run: crystal tool format --check
