name: clim format-check & spec_completion

on: [push]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: format-check & spec_completion
      run: make format-check spec_completion
