name: clim spec_completion

on: [push]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install crystal
      run: curl -fsSL https://crystal-lang.org/install.sh | sudo bash
    - name: spec_completion
      run: make spec_completion
