name: spec1

on: [push]

jobs:
  spec:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Run tests
        run: make spec/1 NUM_OF_JOBS=5
